const muted='#898781',grid='#e1e0d9',money=(v)=>'$'+v;
const COL={weekday:'#898781',friday:'#2a78d6',saturday:'#008300',sunday:'#d55181'};
const SEED={weekday:[[1,57],[8,57],[15,57],[29,33],[57,20],[92,20]],friday:[[4,77],[11,77],[18,77],[32,57],[46,57],[60,35]],saturday:[[5,77],[12,43],[33,26],[89,20]],sunday:[[6,57],[34,43],[62,20]],rtSatSun:[[6,134],[34,69],[62,40]],rtFriSun:[[5,134],[33,100],[61,55]]};
const pts=(a)=>a.map(([x,y])=>({x,y}));
const bandPlugin={id:'band',beforeDraw(chart){if(chart.canvas.id!=='c1')return;const {ctx,chartArea:a,scales:{x,y}}=chart;if(!x||!a)return;const x1=x.getPixelForValue(42),x2=x.getPixelForValue(63);ctx.save();ctx.fillStyle='rgba(0,131,0,0.08)';ctx.fillRect(x1,a.top,x2-x1,a.bottom-a.top);const yf=y.getPixelForValue(20);ctx.strokeStyle='rgba(137,135,129,0.9)';ctx.setLineDash([5,4]);ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.left,yf);ctx.lineTo(a.right,yf);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#2f7d32';ctx.font='600 11px sans-serif';ctx.fillText('sweet spot',x1+6,a.top+14);ctx.fillStyle=muted;ctx.fillText('$20 floor',a.left+6,yf-5);ctx.restore();}};
let c1,c3,c4;
function baseOpts(xmax,ymax,xl,yl){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:(c)=>(c.dataset.label?c.dataset.label+': ':'')+'$'+c.parsed.y+(c.parsed.x!=null?' @ '+c.parsed.x+'d':'')}}},scales:{x:{type:'linear',min:0,max:xmax,title:{display:true,text:xl,color:muted},ticks:{color:muted,callback:(v)=>v+'d'},grid:{display:false}},y:{min:0,max:ymax,title:{display:true,text:yl,color:muted},ticks:{color:muted,callback:money},grid:{color:grid}}}};}
function seedC1(){c1=new Chart(document.getElementById('c1'),{type:'line',plugins:[bandPlugin],data:{datasets:[{label:'Weekday',data:pts(SEED.weekday),borderColor:COL.weekday,backgroundColor:COL.weekday,borderWidth:2,borderDash:[5,4],tension:.3,pointRadius:3},{label:'Friday out',data:pts(SEED.friday),borderColor:COL.friday,backgroundColor:COL.friday,borderWidth:2,tension:.3,pointRadius:4},{label:'Saturday out',data:pts(SEED.saturday),borderColor:COL.saturday,backgroundColor:COL.saturday,borderWidth:2,tension:.3,pointRadius:4,pointStyle:'rectRot'},{label:'Sunday return',data:pts(SEED.sunday),borderColor:COL.sunday,backgroundColor:COL.sunday,borderWidth:2,tension:.3,pointRadius:4,pointStyle:'triangle'}]},options:baseOpts(95,90,'Days booked before departure','Cheapest coach')});}
function seedC3(){c3=new Chart(document.getElementById('c3'),{type:'line',data:{datasets:[{label:'Sat + Sun',data:pts(SEED.rtSatSun),borderColor:COL.saturday,backgroundColor:COL.saturday,borderWidth:2,tension:.3,pointRadius:5,pointStyle:'rectRot'},{label:'Fri + Sun',data:pts(SEED.rtFriSun),borderColor:COL.friday,backgroundColor:COL.friday,borderWidth:2,tension:.3,pointRadius:5}]},options:baseOpts(70,150,'Days booked before departure','Round-trip total')});}
function initDashboard(){
new Chart(document.getElementById('c2'),{type:'line',data:{labels:['7:26a','9:39a','10:44a','12:46p','2:22p','4:14p','7:03p','7:27p','9:01p','9:42p'],datasets:[{data:[77,105,105,105,77,105,134,161,105,57],borderColor:'#eb6834',backgroundColor:'rgba(235,104,52,.10)',borderWidth:2,fill:true,tension:.35,pointRadius:4,pointBackgroundColor:'#eb6834',pointBorderColor:'#fff',pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:(c)=>'$'+c.parsed.y+' — '+c.label}}},scales:{x:{title:{display:true,text:'Departure time',color:muted},ticks:{color:muted,autoSkip:false,maxRotation:45},grid:{display:false}},y:{min:0,max:180,title:{display:true,text:'Cheapest coach',color:muted},ticks:{color:muted,callback:money},grid:{color:grid}}}}});
seedC1();seedC3();
document.getElementById('loadBtn').onclick=()=>document.getElementById('csvInput').click();
document.getElementById('csvInput').onchange=(e)=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{ingest(parseCSV(r.result));}catch(err){document.getElementById('loadStatus').textContent='Could not read file: '+err.message;}};r.readAsText(f);};
}
function parseCSV(txt){const lines=txt.trim().split(/\r?\n/).filter(l=>l.length);const head=lines[0].split(',').map(s=>s.trim());const idx=(n)=>head.indexOf(n);const rows=[];for(let i=1;i<lines.length;i++){const c=lines[i].split(',');const num=(v)=>{v=(v||'').trim();return v===''?null:parseFloat(v);};rows.push({captured:(c[idx('captured_date')]||'').trim(),travel:(c[idx('travel_date')]||'').trim(),dow:(c[idx('day_of_week')]||'').trim(),dir:(c[idx('direction')]||'').trim(),days:num(c[idx('days_ahead')]),low:num(c[idx('lowest_coach_usd')]),seats:num(c[idx('seats_at_lowest')]),next:num(c[idx('next_coach_usd')]),acela:num(c[idx('acela_business_usd')])});}return rows.filter(r=>r.low!=null&&r.days!=null&&r.dow);}
const BUCKETS=[[0,9,5],[10,19,15],[20,34,27],[35,49,42],[50,69,60],[70,120,90]];
function bandFor(rows){const out=[];for(const [lo,hi,mid] of BUCKETS){const vals=rows.filter(r=>r.days>=lo&&r.days<=hi).map(r=>r.low).sort((a,b)=>a-b);if(!vals.length)continue;out.push({x:mid,med:vals[Math.floor((vals.length-1)/2)],min:vals[0],max:vals[vals.length-1]});}return out;}
function legRows(rows,dow,dir){return rows.filter(r=>r.dow===dow&&r.dir===dir);}
function hexA(hex,a){const n=parseInt(hex.slice(1),16);return 'rgba('+((n>>16)&255)+','+((n>>8)&255)+','+(n&255)+','+a+')';}
function weekendKey(r){const d=new Date(r.travel+'T00:00:00');const off={Fri:1,Sat:0,Sun:-1}[r.dow];if(off==null)return null;d.setDate(d.getDate()+off);return d.toISOString().slice(0,10);}
function ingest(rows){
  if(!rows.length){document.getElementById('loadStatus').textContent='No valid fare rows found.';return;}
  const caps=[...new Set(rows.map(r=>r.captured))].sort();
  document.getElementById('loadStatus').innerHTML='<b>Live:</b> '+rows.length+' fares · '+caps.length+' day(s) · '+caps[0]+' → '+caps[caps.length-1];
  document.getElementById('metaline').textContent='Live from fare log · '+rows.length+' samples · captures '+caps[0]+'–'+caps[caps.length-1];
  const sb=document.getElementById('staleBanner'),ageDays=Math.floor((Date.now()-new Date(caps[caps.length-1]+'T00:00:00'))/86400000);
  if(ageDays>2){sb.style.display='block';sb.textContent='⚠ Newest capture is '+caps[caps.length-1]+' ('+ageDays+' days ago) — the daily tracker may have stopped running. Fares below could be outdated.';}else sb.style.display='none';
  const legs=[['friday','Fri','NHV-BOS',COL.friday],['saturday','Sat','NHV-BOS',COL.saturday],['sunday','Sun','BOS-NHV',COL.sunday]];
  const ds=[{label:'Weekday (seed)',data:pts(SEED.weekday),borderColor:COL.weekday,backgroundColor:COL.weekday,borderWidth:2,borderDash:[5,4],tension:.3,pointRadius:2}];
  legs.forEach(([k,dow,dir,col])=>{const b=bandFor(legRows(rows,dow,dir));if(!b.length)return;const rgba=hexA(col,0.13);ds.push({label:dow+' max',data:b.map(p=>({x:p.x,y:p.max})),borderColor:'transparent',backgroundColor:rgba,pointRadius:0,fill:'+1',tension:.3});ds.push({label:dow+' min',data:b.map(p=>({x:p.x,y:p.min})),borderColor:'transparent',backgroundColor:rgba,pointRadius:0,fill:false,tension:.3});ds.push({label:dow+' median',data:b.map(p=>({x:p.x,y:p.med})),borderColor:col,backgroundColor:col,borderWidth:2,tension:.3,pointRadius:4});});
  c1.destroy();c1=new Chart(document.getElementById('c1'),{type:'line',plugins:[bandPlugin],data:{datasets:ds},options:baseOpts(95,90,'Days booked before departure','Cheapest coach')});
  rebuildRT(rows);forecast(rows);buildTrajectory(rows);buildScarcity(rows,caps[caps.length-1]);buildRecommendation(rows,caps[caps.length-1]);
}
function rebuildRT(rows){const latest=[...new Set(rows.map(r=>r.captured))].sort().pop();const lr=rows.filter(r=>r.captured===latest);const byWk={};lr.forEach(r=>{const k=weekendKey(r);if(!k)return;const o=byWk[k]=byWk[k]||{};o[r.dow]=Math.min(o[r.dow]??Infinity,r.low);if(r.dow==='Sat')o.satDays=r.days;});const satPts=[],friPts=[];Object.values(byWk).forEach(o=>{if(o.satDays==null||o.Sun==null)return;if(o.Sat<Infinity)satPts.push({x:o.satDays,y:o.Sat+o.Sun});if(o.Fri<Infinity)friPts.push({x:o.satDays,y:o.Fri+o.Sun});});satPts.sort((a,b)=>a.x-b.x);friPts.sort((a,b)=>a.x-b.x);const xmax=Math.max(70,...satPts.map(p=>p.x),...friPts.map(p=>p.x))+5;const ymax=Math.max(150,...satPts.map(p=>p.y),...friPts.map(p=>p.y))+10;c3.destroy();c3=new Chart(document.getElementById('c3'),{type:'line',data:{datasets:[{label:'Sat + Sun',data:satPts,borderColor:COL.saturday,backgroundColor:COL.saturday,borderWidth:2,tension:.3,pointRadius:5,pointStyle:'rectRot'},{label:'Fri + Sun',data:friPts,borderColor:COL.friday,backgroundColor:COL.friday,borderWidth:2,tension:.3,pointRadius:5}]},options:baseOpts(xmax,ymax,'Days before departure (Saturday)','Round-trip total')});}
function forecast(rows){
  const box=document.getElementById('forecastBox');
  const legs=[['Friday out','Fri','NHV-BOS',COL.friday],['Saturday out','Sat','NHV-BOS',COL.saturday],['Sunday return','Sun','BOS-NHV',COL.sunday]];
  let html='<table><tr><th>Leg</th><th>Modeled floor</th><th>Book by</th><th>Fit pts</th></tr>';let any=false;
  legs.forEach(([name,dow,dir,col])=>{
    const m={};legRows(rows,dow,dir).forEach(r=>{m[r.days]=Math.min(m[r.days]??Infinity,r.low);});
    const P=Object.entries(m).map(([d,y])=>({d:+d,y}));
    if(P.length<3){html+='<tr><td>'+name+'</td><td colspan="3" style="color:var(--muted)">need ≥3 lead-times ('+P.length+' so far)</td></tr>';return;}
    const floor=Math.min(...P.map(p=>p.y));
    const xs=P.map(p=>p.d),ys=P.map(p=>Math.log(Math.max(p.y-floor,1)));
    const n=xs.length,sx=xs.reduce((a,b)=>a+b,0),sy=ys.reduce((a,b)=>a+b,0),sxx=xs.reduce((a,b)=>a+b*b,0),sxy=xs.map((x,i)=>x*ys[i]).reduce((a,b)=>a+b,0);
    const den=(n*sxx-sx*sx);const b=den!==0?(n*sxy-sx*sy)/den:0;const a=(sy-b*sx)/n;const A=Math.exp(a),k=-b;
    let bookBy;if(k>0.0008){const ds=Math.log(Math.max(A/3,1))/k;bookBy=ds>7?'~'+Math.round(ds/7)+' weeks ahead':'~1 week ahead (drops fast)';}else bookBy='stays flat — book anytime';
    html+='<tr><td><span style="color:'+col+'">●</span> '+name+'</td><td class="num">$'+floor+'</td><td>'+bookBy+'</td><td class="num">'+P.length+'</td></tr>';any=true;
  });
  html+='</table>';box.className=any?'':'placeholder';
  box.innerHTML=any?html+'<p class="note">Model: fare = floor + A·e^(−k·days-ahead), least-squares on logged points. Early fits are directional; they tighten as the log grows.</p>':'Load a log with ≥3 lead-times per leg to model floors.';
}
function buildTrajectory(rows){
  const wknds=[...new Set(rows.map(weekendKey).filter(Boolean))].sort();const sel=document.getElementById('trajSelect');sel.innerHTML='';wknds.forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent='Weekend of Sat '+k;sel.appendChild(o);});
  const caps=[...new Set(rows.map(r=>r.captured))].sort();
  if(caps.length<2){document.getElementById('trajPlaceholder').style.display='block';document.getElementById('trajControls').style.display='none';document.getElementById('trajBox').style.display='none';return;}
  document.getElementById('trajPlaceholder').style.display='none';document.getElementById('trajControls').style.display='block';document.getElementById('trajBox').style.display='block';
  const draw=()=>{const k=sel.value;const wk=rows.filter(r=>weekendKey(r)===k);const wc=[...new Set(wk.map(r=>r.captured))].sort();const ser=wc.map(cap=>{const s=wk.filter(r=>r.captured===cap);const fri=Math.min(Infinity,...s.filter(r=>r.dow==='Fri').map(r=>r.low));const sat=Math.min(Infinity,...s.filter(r=>r.dow==='Sat').map(r=>r.low));const sun=Math.min(Infinity,...s.filter(r=>r.dow==='Sun').map(r=>r.low));const out=Math.min(fri,sat);return (out<Infinity&&sun<Infinity)?{x:cap,y:out+sun}:null;}).filter(Boolean);const labels=ser.map(p=>p.x),vals=ser.map(p=>p.y);if(c4)c4.destroy();c4=new Chart(document.getElementById('c4'),{type:'line',data:{labels,datasets:[{label:'Cheapest round trip',data:vals,borderColor:'#534ab7',backgroundColor:'rgba(83,74,183,.10)',borderWidth:2,fill:true,tension:.3,pointRadius:4,pointBackgroundColor:'#534ab7',pointBorderColor:'#fff',pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:(c)=>'$'+c.parsed.y+' on '+c.label}}},scales:{x:{title:{display:true,text:'Capture date',color:muted},ticks:{color:muted},grid:{display:false}},y:{beginAtZero:false,title:{display:true,text:'Round-trip total',color:muted},ticks:{color:muted,callback:money},grid:{color:grid}}}}});const v=document.getElementById('trajVerdict');if(vals.length){const cur=vals[vals.length-1],min=Math.min(...vals),trend=vals.length>=3?cur-vals[vals.length-3]:0;let msg,cls;if(cur<=min+2&&cur<=60){msg='At/near floor — book now.';cls='best';}else if(trend>4){msg='Rising — book soon.';cls='win';}else{msg='Drifting down — okay to wait.';cls='';}v.innerHTML='<span class="'+cls+'">'+msg+'</span> <span style="color:var(--muted)">(now $'+cur+', low $'+min+')</span>';}else v.textContent='';};
  sel.onchange=draw;draw();
}
function buildScarcity(rows,latest){const lr=rows.filter(r=>r.captured===latest&&r.seats!=null).sort((a,b)=>a.seats-b.seats);const box=document.getElementById('scarcityBox');if(!lr.length){box.className='placeholder';box.textContent='Latest capture had no seats-left data.';return;}box.className='';let h='<table><tr><th>Travel date</th><th>Leg</th><th>Lowest</th><th>Seats</th><th>Next</th></tr>';lr.slice(0,10).forEach(r=>{const s=r.seats<=2;h+='<tr><td>'+r.travel+' ('+r.dow+')</td><td>'+r.dir+'</td><td class="num">$'+r.low+'</td><td class="num '+(s?'scarce':'')+'">'+r.seats+(s?' ⚠':'')+'</td><td class="num">'+(r.next!=null?'$'+r.next:'—')+'</td></tr>';});h+='</table><p class="note">⚠ = ≤2 seats at the lowest price; expect a jump to the next price.</p>';box.innerHTML=h;}
function buildRecommendation(rows,latest){const lr=rows.filter(r=>r.captured===latest);const byWk={};lr.forEach(r=>{const k=weekendKey(r);if(!k)return;const o=byWk[k]=byWk[k]||{};o[r.dow]=Math.min(o[r.dow]??Infinity,r.low);if(r.dow==='Sat')o.days=r.days;});let best=null;Object.entries(byWk).forEach(([k,o])=>{if(o.Sun==null)return;const out=Math.min(o.Fri??Infinity,o.Sat??Infinity);if(out===Infinity)return;const rt=out+o.Sun;const day=(o.Sat!=null&&o.Sat<=(o.Fri??Infinity))?'Saturday':'Friday';if(!best||rt<best.rt)best={k,rt,day};});if(!best)return;document.getElementById('kpiCheapRT').textContent='$'+best.rt;const fl=best.rt<=60;document.getElementById('recHead').textContent='Cheapest now: '+best.day+' out + Sunday back, weekend of '+best.k+' — about $'+best.rt+' round trip.';document.getElementById('recBody').innerHTML=fl?'At/near the floor and unlikely to fall much further — <b>good to book</b>. Check the trajectory for your exact weekend first.':'Still above the ~$40 floor. If your weekend is &gt;2 weeks out, watch a few more days — the trajectory shows if it is still dropping. Saturday beats Friday at the same lead time.';}
// in a browser: init charts and auto-load the committed CSV (works on GitHub Pages / any http server); skipped under Node so the pure helpers can be require()d by tests
if(typeof document!=='undefined'){initDashboard();fetch('data/amtrak_fare_log.csv',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('http '+r.status);return r.text();}).then(t=>ingest(parseCSV(t))).catch(()=>{document.getElementById('loadStatus').innerHTML='Auto-load unavailable (opened via file://). Click <b>Load fare log</b> and pick <b>data/amtrak_fare_log.csv</b>.';document.getElementById('metaline').textContent='Showing seed snapshot — load the CSV to go live.';});}
if(typeof module!=='undefined'&&module.exports){module.exports={parseCSV,weekendKey,bandFor};}
